@startuml actoin-domain

skinparam classFontColor automatic
skinparam classHeaderBackgroundColor<<Important>> #EA3652
hide stereotype

package Domain <<Rectangle>> {

    abstract class Player {
    }

}

package Application <<Rectangle>> {

    class Game <<Important>> {
        - List<Player> players
    }

    class GamePlayer{
    }

}

GamePlayer -d-|>Player
Game "1" o-l- "n" Player


@enduml