@startuml actoin-domain

skinparam classFontColor automatic
skinparam classHeaderBackgroundColor<<Important>> #EA3652
hide stereotype

package Domain <<Rectangle>> {

    interface Instruction <<Important>> {

        + void execute(Player player, MoveState moveState, Stock stock)
        + String getName()

    }

    class Action {
        - List<Instruction> instructions

        + Action(Instructions... instructions)
        + List<Instruction> getInstructions()
    }

}

package Application <<Rectangle>> {

    package "Many different Instructions" <<Cloud>> {
    }

}

"Many different Instructions" -d-|> Instruction
"Many different Instructions" - Action : per Konstruktur übergeben >
Action "1" o-r- "n" Instruction

@enduml